### ISSUE TITLE
Question of libraries, cell names

### ISSUE THREAD

**Issue by ChuanXu1** [Single-Cell-Genomics-Group-CNAG-CRG/TonsilAtlas#3]
Hi TonsilAtlas Team (@massonix ),

I am a bit confused on the sample sequencing strategy of this data. For example, when I searched `ERS19337242` at your repo [E-MTAB-13687](https://www.ebi.ac.uk/biostudies/arrayexpress/studies/E-MTAB-13687/sdrf), it returns four _RNA_ files (at page 2 of the search result), including P1, P2, P3, P4. Among them, P1 and P2 are prefixed with `ulx1v6sz_8a2nvf1c`, and P2 and P2 are prefixed with `wdp0p728_jf6w68km`.

If I understand correctly, these four will be specified in one Cell Ranger, such as:
```
multiome.BCLL-8-T.BCLLATLAS_42.ulx1v6sz_8a2nvf1c.182653.RNA.P1.R1.fastq.gz,
multiome.BCLL-8-T.BCLLATLAS_42.ulx1v6sz_8a2nvf1c.182653.RNA.P2.R1.fastq.gz,
multiome.BCLL-8-T.BCLLATLAS_42.wdp0p728_jf6w68km.182654.RNA.P3.R1.fastq.gz,
multiome.BCLL-8-T.BCLLATLAS_42.wdp0p728_jf6w68km.182654.RNA.P4.R1.fastq.gz
```
, and generate one Cell Ranger output.

However, in your Seurat object, the cell names have two classes, including both `wdp0p728_jf6w68km_` and `ulx1v6sz_8a2nvf1c`. Does this mean that `ERS19337242`  actually has two samples, and two Cell Ranger runs should be conducted for `wdp0p728_jf6w68km_` and `ulx1v6sz_8a2nvf1c`, respectively?

Please let me know which one is correct (i.e., for `ERS19337242`, do i need one or two cell ranger runs).

Thanks.

**Comment by massonix** [comment]
Hi @ChuanXu1 !

I would recommend that you use the naming that we specify in the README of this repository to navigate the files, instead of the names given by ArrayExpress. We use the following convention

[TECHNOLOGY].[DONOR_ID].[SUBPROJECT].[GEM_ID].[LIBRARY_ID].[LIBRARY_TYPE].[PAIR_ID].[READ].fastq.gz

in the README you'll find an explanation of each field. In essence, you should aim to map all fastqs that share the same "gem_id" together (i.e. ulx1v6sz_8a2nvf1c), because this identifies each 10X Channel. In the case of Multiome, for a given gem_id you can have two different library_ids (ATAC and RNA)

Hope that helps!

Ramon

**Comment by ChuanXu1** [comment]
Thank you!
